### ISSUE TITLE
error when run test_swt.py

### ISSUE THREAD

**Issue by catmonkeylee** [nlintz/StrokeWidthTransform#1]
When I run python2.7 test_swt.py.  In source code , I can not find the function "adaptiveEdges", can you help me ?

Traceback (most recent call last):
  File "test_swt.py", line 102, in <module>
    test_first_pass()
  File "test_swt.py", line 71, in test_first_pass
    edges = swt.adaptiveEdges(img)
AttributeError: 'module' object has no attribute 'adaptiveEdges'

**Comment by yangysc** [comment]
Excuse me ,I have this issue too.Have you fixed this?
I change this code by using "cv2.Canny".But when I continue to run ,I find another issue,
"
 File "lib\fastRay.pyx", line 65, in lib.fastRay.castRay (lib\fastRay.c:1778)
    cdef float rayDirection = angles[row][column]
IndexError: index 132944720 is out of bounds for axis 0 with size 640
"
Can you help me with this issue？

**Comment by jonahdelaware** [comment]
@yangysc Did you solve this error? I got the same one. 
Kind regards

**Comment by rbharu** [comment]
> When I run python2.7 test_swt.py. In source code , I can not find the function "adaptiveEdges", can you help me ?
> 
> Traceback (most recent call last):
> File "test_swt.py", line 102, in 
> test_first_pass()
> File "test_swt.py", line 71, in test_first_pass
> edges = swt.adaptiveEdges(img)
> AttributeError: 'module' object has no attribute 'adaptiveEdges'

Hi,
i got the same error, did you solve this...
